version: '3'


services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    links: 
      - mongo
    stdin_open: true
    tty: true
    volumes:
      - "/Users/bawa/projects/git/docker-centos56:/opt/app/public"
      - "./.docker/nginx/conf.d:/etc/nginx/conf.d"
    command: nginx
    networks:
      - centos56    
  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    expose:
      - "9000"
      - "9006"
    volumes:
      - "/Users/bawa/projects/git/docker-centos56:/opt/app/public"
      - "./.docker/php-fpm/php-fpm.conf:/etc/php-fpm.conf"
      - "./.docker/php-fpm/www.conf:/etc/php-fpm.d/www.conf"
      - "./.docker/php-fpm/php.ini:/etc/php.ini"
      - "./.docker/php-fpm/xdebug.ini:/etc/php.d/xdebug.ini"

    depends_on: 
      - mongo
    links: 
      - mongo
    stdin_open: true
    tty: true
    command: php-fpm
    networks:
      - centos56
  mysql:
    image: mysql:5.7.29
    container_name: mysql56
    restart: unless-stopped
    tty: true
    ports:
    - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
    - centos56
  mongo:
    image: mongo
    container_name: mongo56
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
    - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./share:/home
      - ./db-data:/data/db
      - ./mongo-config:/data/configdb
    networks:
      - centos56
networks:
  centos56: