imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        #cookie_lifetime: 10
    #session:
        #default_locale: %locale%
        #lifetime:       10
        #auto_start:     true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        edustack_schoolname: %edustack_schoolname%
        edu_account_helper: "@edu.account.helper"
        edu_exam_helper: "@edu.exam.helper"
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017


    default_database: ypschd

    document_managers:
            default:
                auto_mapping: trueld
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
             enum: string
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
#swiftmailer:
  #  transport: %mailer_transport%
  #  host:      %mailer_host%
   # username:  %mailer_user%
   # password:  %mailer_password%
   # spool:     { type: memory }

swiftmailer:
    transport:  gmail
    host:       null
    username:   harkamalpreetkaur@indivar.com
    password:   test
    encryption: ssl
    auth_mode: login
#implement ckeditor

 #ckeditor settings

ivory_ck_editor:
    #default_config: default
    base_path: "ckeditor"
    js_path: "ckeditor/config.js"
    plugins:
        wordcount:
            path:     "/edu/circularbundle/resources/public/wordcount/"
            filename: "plugin.js"

knp_snappy:
    pdf:
        enabled:    true
        binary:     xvfb-run wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     xvfb-run wkhtmltopdf
        options:    []

#services:
 #   login.twig.dev_extension:
 #       class: Edu/LoginBundle/Twig/DevExtension
 #       tags:
 #           - { name: twig.extension }
cspoo_swiftmailer_mailgun:
    key: "key-9698fb30f2d2b259cb910e1091538ff3"
    domain: "testaccount.edubold.com"
    http_client: '' # Optional. Defaults to null and uses discovery to find client.

# Swiftmailer Configuration
swiftmailer:
    transport: "mailgun"
    spool:     { type: memory } # This will start sending emails on kernel.terminate event

doctrine_mongodb:
    connections:
        default:
            server: mongodb://mongo:27017
            options: {}
    document_managers:
        default:
            auto_mapping: true

